# Generated by Django 3.0 on 2019-12-05 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='', verbose_name='Файл меню')),
            ],
            options={
                'verbose_name': 'Файл меню',
                'verbose_name_plural': 'Файл меню',
            },
        ),
    ]
