version: '3'

services:

  db:
    build: Dockerfiel.db
    networks:
      - db_network
    volumes:
      - db_volume

  underwonder:
    build: .
    volumes:
      - .:/underwonder
      - static_volume:/underwonder/staticfiles
    networks:
      - nginx_network
      - db_network
    depends_on:
      - db

  nginx:
    image: nginx:1.13
    ports:
      - 80:80
    volumes:
      - ./config/nginx/conf.d:/etc/nginx/conf.d
      - static_volume:/underwonder/staticfiles
    depends_on:
      - underwonder
    networks:
      - nginx_network

networks:  # <-- and here
  nginx_network:
    driver: bridge
  db_network:
    driver: bridge

volumes:
  db_volume:
  static_volume:

