# Generated by Django 2.1.3 on 2018-11-26 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drinks', '0003_auto_20181126_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drinkitem',
            name='weight',
            field=models.CharField(blank=True, max_length=20, verbose_name='Вес/Литраж'),
        ),
    ]
