# Generated by Django 2.1.3 on 2018-11-25 10:47

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BreakfastItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=120, verbose_name='Наименование позиции')),
                ('title_eng', models.CharField(default='', max_length=120, verbose_name='Наименование позиции ENG')),
                ('content', models.TextField(blank=True, default='', verbose_name='Описание категории')),
                ('price', models.FloatField(validators=[django.core.validators.MinValueValidator(0.1, 'Цена не может иметь отрицательное значение')], verbose_name='Цена')),
                ('weight', models.FloatField(validators=[django.core.validators.MinValueValidator(0.1, 'Укажите реальный вес')], verbose_name='Вес/Литраж')),
                ('parent', models.ForeignKey(blank=True, default=None, help_text='Если позиция может иметь несколько вариантов подачи, выбрать её родительскую.Пример - омлет в разделе Завтраков.', null=True, on_delete=django.db.models.deletion.CASCADE, to='breakfasts.BreakfastItem', verbose_name='Родительская позиция')),
            ],
            options={
                'verbose_name': 'Позиция завтрака',
                'verbose_name_plural': 'Позиции завтрака',
                'db_table': 'breakfast_items',
            },
        ),
    ]
