# Generated by Django 2.1.3 on 2018-11-26 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breakfasts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='breakfastitem',
            name='bold',
            field=models.BooleanField(default=False, help_text='Выбирете этот параметр если хотите,         чтобы наименование позиции было выделено жирным текстом', verbose_name='Наименование жирным текстом'),
        ),
    ]
