# Generated by Django 2.1.3 on 2018-11-27 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breakfasts', '0006_auto_20181127_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breakfastitem',
            name='content_eng',
            field=models.TextField(blank=True, default='', verbose_name='Описание позиции ENG'),
        ),
    ]
