# Generated by Django 2.1.3 on 2018-11-26 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='title_eng',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='Наименование позиции ENG'),
        ),
    ]
