# Generated by Django 2.1.3 on 2018-11-27 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_menu', '0004_auto_20181126_2201'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='content_eng',
            field=models.TextField(blank=True, default='', verbose_name='Описание позиции'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='content',
            field=models.TextField(blank=True, default='', verbose_name='Описание позиции'),
        ),
    ]
