# Generated by Django 2.1.3 on 2018-11-29 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_menu', '0006_auto_20181127_2020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menucategory',
            name='small_description',
        ),
    ]
