# Generated by Django 3.0 on 2019-12-05 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(editable=False, max_length=120, verbose_name='Имя секции главного меню')),
                ('content', models.TextField(verbose_name='Текст секции')),
                ('content_eng', models.TextField(verbose_name='Текст секции ENG')),
            ],
            options={
                'verbose_name': 'Раздел на главной странице',
                'verbose_name_plural': 'Разделы на главной странице',
                'db_table': 'index_page_content',
            },
        ),
    ]
