# Generated by Django 2.1.3 on 2018-11-28 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Имя секции главного меню')),
                ('content', models.TextField(help_text='Абзацы разделять пустой строкой. Так же работает перенос строки.', verbose_name='Текст секции')),
            ],
            options={
                'verbose_name': 'Главня страница',
                'db_table': 'index_page_content',
            },
        ),
    ]
