# Generated by Django 2.1.3 on 2018-11-28 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='section',
            options={'verbose_name': 'Раздел на главной странице', 'verbose_name_plural': 'Разделы на главной странице'},
        ),
        migrations.AddField(
            model_name='section',
            name='content_eng',
            field=models.TextField(default='a', help_text='Абзацы разделять пустой строкой. Так же работает перенос строки.', verbose_name='Текст секции ENG'),
            preserve_default=False,
        ),
    ]
