# Generated by Django 2.1.3 on 2018-11-28 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_auto_20181128_2245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='content',
            field=models.TextField(verbose_name='Текст секции'),
        ),
        migrations.AlterField(
            model_name='section',
            name='content_eng',
            field=models.TextField(verbose_name='Текст секции ENG'),
        ),
    ]
