# Generated by Django 2.1.3 on 2018-11-28 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_auto_20181128_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='title',
            field=models.CharField(editable=False, max_length=120, verbose_name='Имя секции главного меню'),
        ),
    ]
